### ISSUE TITLE
Auto-Update applying the wrong SHASUM

### ISSUE THREAD

**Issue by mtslzr** [mtslzr/homebrew-marmaduke-chromium#10]
Looks like the auto-update commit from @S0urceC0der is applying an incorrect hash for Ungoogled (fixed it manually in #9, but it was reverted overnight). Should figure out what's up and fix it.

**Comment by S0urceC0der** [comment]
A new arm64 version added to the download list, so the script download the wrong file. fixed in 
 f6ac2d5c92089c8722b55ca8f79bdcc05b3a6210
