### ISSUE TITLE
Error: SHA256 mismatch

### ISSUE THREAD

**Issue by JanekMazowiecki** [mtslzr/homebrew-marmaduke-chromium#14]
Error: mtslzr/marmaduke-chromium/marmaduke-chromium: SHA256 mismatch
Expected: 3fe5f2011b9e4a03565078076da4ba37d1315ff015f10fd5faf0d57292bbe0e6
Actual: ec47c6015ec77dca939ac52f62f025eb09c7b570c9477385fff81f1f59b4a324

**Comment by williamchange** [comment]
Had the same issue from homebrew.
