### ISSUE TITLE
Bug: Anonymize local IPs exposed by WebRTC not working

### ISSUE THREAD

**Issue by Kees1958** [mtslzr/homebrew-marmaduke-chromium#21]
When I enable the flag #enable-webrtc-hide-local-ips-with-mdns Local IP Address still shows on browserleaks

**Comment by mtslzr** [comment]
Apologies, but this repo is just a macOS package for Chromium, not Chromium itself. You might want to try https://bugs.chromium.org/p/chromium/issues/list.
