### ISSUE TITLE
Feature request for chrome://flags/#clear-data-on-exit use 

### ISSUE THREAD

**Issue by Kees1958** [mtslzr/homebrew-marmaduke-chromium#22]
At the moment all data is cleared (which is great enhancement compared to Chrome)

Would it be possible to add an (extra) option to exclusion for site-permissions?

**Comment by mtslzr** [comment]
Apologies, but this repo is just a macOS package for Chromium, not Chromium itself. You might want to try https://bugs.chromium.org/p/chromium/issues/list.

**Comment by Kees1958** [comment]
It is not a chrome flag, it is a flag specially added to marmaduke

**Comment by mtslzr** [comment]
And this repo isn't building markmaduke, but merely packaging it for Homebrew.
