### ISSUE TITLE
Unable to install marmaduke-chromium-ungoogled

### ISSUE THREAD

**Issue by knvzzz** [mtslzr/homebrew-marmaduke-chromium#35]
brew install marmaduke-chromium-ungoogled
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################### 100.0%
==> Downloading https://github.com/macchrome/macstable/releases/download/v119.60
curl: (22) The requested URL returned error: 404                               

Error: Download failed on Cask 'marmaduke-chromium-ungoogled' with message: Download failed: https://github.com/macchrome/macstable/releases/download/v119.6045.123-M119.0.6045.123-r1204232-macOS/Chromium.app.ungoogled-119.0.6045.123.tar.xz

**Comment by S0urceC0der** [comment]
The cause of this bug may be that upstream released a new version 119.0.6045.123  and then removed it later. It has been fixed now. The latest version is restored back to 119.6045.112.
